# ==============================================================================
# config - sidekiq
# ==============================================================================
development:
  :verbose: true
  :concurrency: 4
:queues:
  - default
